export const CREATE_USER = 'CREATE_CUSTOMER';
export const CREATE_USER_SUCCESS = 'CREATE_CUSTOMER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_CUSTOMER_SUCCESS';

export const LIST_ALL_USERS = 'LIST_ALL_CUSTOMERS';
export const LIST_ALL_USERS_SUCCESS = 'LIST_ALL_CUSTOMERS_SUCCESS';
export const LIST_ALL_USERS_FAILURE = 'LIST_ALL_CUSTOMERS_FAILURE';

export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const CREATE_STORY = 'CREATE_STORY';
export const CREATE_STORY_SUCCESS = 'CREATE_STORY_SUCCESS';
export const CREATE_STORY_FAILURE = 'CREATE_STORY_FAILURE';

export const GET_ALL_STORIES = 'GET_ALL_STORIES';
export const GET_ALL_STORIES_SUCCESS = 'GET_ALL_STORIES_SUCCESS';
export const GET_ALL_STORIES_FAILURE = 'GET_ALL_STORIES_FAILURE';

export const GET_USER_STORIES = 'GET_USER_STORIES';
export const GET_USER_STORIES_FAILURE = 'GET_USER_STORIES_FAILURE';
export const GET_USER_STORIES_SUCCESS = 'GET_USER_STORIES_SUCCESS';

export const GET_STORY = 'GET_STORY';
export const GET_STORY_SUCCESS = 'GET_STORY_SUCCESS';
export const GET_STORY_SUCCESS_FAILURE = 'GET_STORY_SUCCESS_FAILURE';